version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ffcpgrds
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: aurpgs_FOMFOCUCFL_dev_ffc_01
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
